name 'raspberry_phoronix'
maintainer 'Jakub Błaszczyk'
maintainer_email 'jakub.blaszczyk@sap.com'
license 'all_rights'
description 'Installs/Configures docker_vlc'
long_description 'Installs/Configures docker_vlc'
version '0.1.6'
