Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "debian8_local"
  c.vm.box_url = "http://apache.pitux.ovh/data/vagrant/debian8_local.box"
  c.vm.hostname = "default-debian8-local"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :virtualbox do |p|
    p.customize ["modifyvm", :id, "--nictype1", "virtio"]
  end
end
